on:
  # allows to manually run the job at any time
  workflow_dispatch:

  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Labels
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          
      - name: Splatnet data
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.splatoon.svg
          token: NOT_NEEDED
          base: ""
          plugin_splatoon: yes
          plugin_splatoon_token: ${{ secrets.SPLATOON_TOKEN }}
